---
- name: Configure dns slave server
  hosts: servers
  become: yes
  vars:
    domain: "domain"
    master_ip4addr: "1.1.1.1"

  tasks:
    - name: Install dns packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - bind9
        - dnsutils

    - name: Copy dns slave config file
      template:
        src: templates/named.conf.local-slave.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: 0644
      notify:
        - Restart dns slave server

    - name: Copy dns config options file
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: 0644
      notify:
        - Restart dns slave server

  handlers:
    - name: Restart dns slave server
      service:
        name: bind9
        state: restarted
...
