---
- name: Configure dns slave server
  hosts: servers
  become: yes
  vars:
    domain: "domain"
    bind_user: "bind"
    bind_group: "bind"
    bind_chroot_dir: "/var/bind/chroot"
    master_ip4addr: "1.1.1.1"

  tasks:
    - include: dns_common.yml

    - name: Copy dns slave config files
      template:
        src: "templates/{{ item.src_file }}"
        dest: "/etc/bind/{{ item.dst_file }}"
        owner: root
        group: bind
        mode: 0644
      with_items:
        - { src_file: "named.conf.local-slave.j2", dst_file: "named.conf.local" }
        - { src_file: "named.conf.options.j2", dst_file: "named.conf.options" }
      notify:
        - Restart dns slave server

  handlers:
    - name: Restart dns slave server
      service:
        name: bind9
        state: restarted
...
