---
- name: Configure dns slave server
  hosts: servers
  become: yes
  vars:
    bind_user: "bind"
    bind_group: "bind"
    bind_chroot_dir: "/var/bind/chroot"
    domain: "domain"
    master_ip4addr: "1.1.1.1"

  tasks:
    - name: Install dns packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - bind9
        - dnsutils

    - name: Set chroot dir for dns server
      lineinfile:
        dest: /etc/default/bind9
        regexp: '^OPTIONS="-u bind'
        line: 'OPTIONS="-u {{ bind_user }} -t {{ bind_chroot_dir }}"'
        state: present

    - name: Create chroot dir for dns server
      file:
        path: "{{ bind_chroot_dir }}/{{ item }}"
        owner: "{{ bind_user }}"
        group: "{{ bind_group }}"
        state: directory
      with_items:
        - etc
        - dev
        - lib
        - usr/sbin
        - var/cache/bind
        - var/run

    - name: mknod devices in chroot dir
      command: "mknod -m 0660 {{ item.dev }} c {{ item.major }} {{ item.minor }}"
      with_items:
      - { dev: "{{ bind_chroot_dir }}/dev/null", major: '1', minor: '3'}
      - { dev: "{{ bind_chroot_dir }}/dev/random", major: '1', minor: '8'}

    - name: Copy dns slave config files
      template:
        src: "templates/{{ item.src_file }}"
        dest: "/etc/bind/{{ item.dst_file }}"
        owner: root
        group: bind
        mode: 0644
      with_items:
        - { src_file: "named.conf.local-slave.j2", dst_file: "named.conf.local" }
        - { src_file: "named.conf.options.j2", dst_file: "named.conf.options" }

    - name: Move original bind config dir to the chrooted one
      command: "mv /etc/bind {{ bind_chroot_dir }}/etc"

    - name: Create a symlink to original bind dir
      file:
        src: "{{ bind_chroot_dir }}/etc/bind"
        dest: /etc/bind
        owner: 0
        group: "{{ bind_group }}"
        state: link

    - name: Copy localtime
      command: "cp /etc/localtime {{ bind_chroot_dir}}/etc/"
...
