---
- name: Configure a docker machine
  hosts: servers
  become: yes
  vars:
    admin_username: false

  tasks:
    - name: Install prereq packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

    - name: Add Docker GPG signing key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Install docker package
      apt:
        name: docker-ce
        update_cache: yes

    - name: Add 'admin' user to docker group when not at production
      user:
        name: "{{ admin_username }}"
        groups: docker
        append: yes
      when: admin_username

    - name: Allow Docker Swarm for IPv4
      iptables_raw:
        name: "docker_swarm_ipv4"
        table: "filter"
        weight: 76
        ipversion: "4"
        keep_unmanaged: no
        rules: |
          -A INPUT -i tun0 -p tcp -m tcp --dport 2377 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
          -A INPUT -i tun0 -p tcp -m tcp --dport 7946 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
          -A INPUT -i tun0 -p udp -m udp --dport 7946 -m state --state NEW -j ACCEPT
          -A INPUT -i tun0 -p udp -m udp --dport 4789 -m state --state NEW -j ACCEPT

    - name: Allow Docker Swarm for IPv6
      iptables_raw:
        name: "docker_swarm_ipv6"
        table: "filter"
        weight: 76
        ipversion: "6"
        keep_unmanaged: no
        rules: |
          -A INPUT -i tun0 -p tcp -m tcp --dport 2377 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
          -A INPUT -i tun0 -p tcp -m tcp --dport 7946 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
          -A INPUT -i tun0 -p udp -m udp --dport 7946 -m state --state NEW -j ACCEPT
          -A INPUT -i tun0 -p udp -m udp --dport 4789 -m state --state NEW -j ACCEPT
...
