---
- name: Configure a docker machine
  hosts: servers
  become: yes
  vars:
    admin_username: false

  tasks:
    - name: Install prereq packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

    - name: Add Docker GPG signing key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Install docker package
      apt:
        name: docker-ce
        update_cache: yes

    - name: Add 'admin' user to docker group when not at production
      user:
        name: "{{ admin_username }}"
        groups: docker
        append: yes
      when: admin_username

...
