---
- name: Install a Let's Encrypt TLS certificate
  hosts: web
  become: yes
  vars:
    cert_domain_name: "www.site.com"
    cert_email: "user@site.com"

  tasks:
    - name: Install Let's Encrypt packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - python-certbot

    - name: Execute certbot command
      shell: certbot certonly --standalone --noninteractive --agree-tos --email {{ cert_email }} -d {{ cert_domain_name }}
...
