---
- name: Manage Linode instances
  hosts: localhost

  vars_prompt:
    - name: "access_token"
      prompt: "Linode access token"

    - name: "hostname"
      private: false

    - name: "root_password"
      prompt: "Image initial root password to be set up"

  tasks:
    - name: Act on a Linode instance (add/remove)
      linode_v4:
        access_token: "{{ access_token | default('li1234') }}"
        label: "{{ hostname }}"
        tags: servers
        type: g6-nanode-1
        region: eu-west
        image: linode/arch
        root_pass: "{{ root_password | default('li1234') }}"
        state: "{{ state | default('present') }}"
      register: linode

    - name: Show results
      debug:
        msg: "{{ linode }}"
...
