---
- name: Manage Linode instances
  hosts: localhost

  vars:
    - state: "present"

  vars_prompt:
    - name: "access_token"
      prompt: "Linode access token"

    - name: "hostname"
      private: false

    - name: "root_password"
      prompt: "Image initial root password to be set up"

  tasks:
    - name: Act on a Linode instance (add/remove)
      linode_v4:
        access_token: "{{ access_token | default('li1234') }}"
        label: "{{ hostname }}"
        tags: servers
        type: g6-nanode-1
        region: eu-west
        image: linode/debian10
        root_pass: "{{ root_password | default('li1234') }}"
        state: "{{ state }}"
      register: linode

    - name: Wait for new host to become active
      wait_for:
        host: "{{ linode.instance.ipv4[0] }}"
        port: 22
        delay: 20
        timeout: 300
      when: state == "present"
...
