---
- name: Client sending logs to a remote rsyslog server
  hosts: servers
  become: yes
  vars:
    syslog_server: "remote.syslog.server"

  tasks:
    - name: Copy rsyslog client config file
      template:
        src: templates/rsyslog-client.conf.j2
        dest: /etc/rsyslog.conf
        backup: yes
        owner: 0
        group: 0
        mode: 0644
      notify:
        - Restart rsyslogd

  handlers:
    - name: Restart rsyslogd
      service:
        name: rsyslog
        state: restarted
...
