---
- name: Disable SSH Password Authentication
  hosts: initials
  become: yes

  tasks:
    - name: Set no password Authentication for SSH daemon
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        insertafter: '^PermitRootLogin'
        state: present
      notify:
        - Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
...
