---
- name: Configure a web server as CDN
  hosts: servers
  become: yes
  vars:
    server_name: "server_name"
    server_admin: "server_admin"
    document_root: "document_root"
    server_cert_file: "server_cert_file"
    server_key_file: "server_key_file"

  tasks:
    - name: Install a web server
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apache2

    - name: Activate SSL module
      apache2_module:
        name: ssl
        state: present

    - name: Create CDN base dir
      file:
        path: /var/www/cdn
        owner: 0
        group: 0
        state: directory

    - name: Copy base CDN config file
      template:
        src: templates/010-cdn.conf.j2
        dest: /etc/apache2/sites-available/010-cdn.conf
        owner: 0
        group: 0
        mode: 0644
      notify:
        - Restart web server

    - name: Activate CDN site
      command: a2ensite 010-cdn
      args:
        creates: /etc/apache2/sites-enabled/010-cdn.conf
      notify:
        - Restart web server

    - name: Deactivate default site
      command: a2dissite 000-default
      args:
        removes: /etc/apache2/sites-enabled/000-default.conf
      notify:
        - Restart web server

  handlers:
    - name: Restart web server
      service:
        name: apache2
        state: restarted
...
