---
- name: Install web proxy server
  pacman:
    name: squid
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: Activate web proxy service
  service:
    name: squid
    enabled: yes
    state: started

- name: Copy base config file
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - Restart web proxy

- name: Allow proxy cache ports for IPv4
  iptables:
    table: filter
    chain: INPUT
    ip_version: ipv4
    protocol: tcp
    destination_port: '3128'
    ctstate: NEW
    in_interface: "{{ proxy_lan_interface | default('eno1') }}"
    jump: ACCEPT
  register: iptables

- name: Save proxy rules for IPv4
  command: iptables-save -t filter -f /etc/iptables/iptables.rules
  when: iptables.changed == true
  notify: Restart iptables firewall

- name: Allow proxy cache ports for IPv6
  iptables:
    table: filter
    chain: INPUT
    ip_version: ipv6
    protocol: tcp
    destination_port: '3128'
    ctstate: NEW
    in_interface: "{{ proxy_lan_interface | default('eno1') }}"
    jump: ACCEPT
  register: ip6tables

- name: Save proxy rules for IPv6
  command: ip6tables-save -t filter -f /etc/iptables/ip6tables.rules
  when: ip6tables.changed == true
  notify: Restart ip6tables firewall
...
