---
- name: New aliases
  command: newaliases

- name: Helo access checks
  command: postalias hash:/etc/postfix/helo_access_checks

- name: Restart postfix
  service:
    name: postfix
    state: restarted
...
