- name: Install CDN packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - apache2

- name: Activate SSL module
  apache2_module:
    name: ssl
    state: present

- name: Create CDN base dir
  file:
    path: "{{ document_root }}"
    owner: 0
    group: 0
    mode: 0755
    state: directory

- name: Clone git rcnd repository
  git:
    repo: 'https://github.com/ronaldoafonso/rcdn.git'
    dest: "{{ document_root }}"
    version: v1.0
  notify:
    - Restart web server

- name: Create CDN base log dir
  file:
    path: "{{ log_dir }}"
    owner: 0
    group: adm
    mode: 0750
    state: directory

- name: Copy base CDN config files
  template:
    src: "{{ item }}.j2"
    dest: /etc/apache2/sites-available/{{ item }}
    owner: 0
    group: 0
    mode: 0644
  loop:
    - 010-cdn-http.conf
    - 010-cdn-https.conf
  notify:
    - Restart web server

- name: Activate CDN sites
  command: a2ensite {{ item }}
  args:
    creates: /etc/apache2/sites-enabled/{{ item }}
  loop:
    - 010-cdn-http.conf
    - 010-cdn-https.conf
  notify:
    - Restart web server

- name: Deactivate default site
  command: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - Restart web server

- name: Activate CDN modules
  command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop:
    - headers
  notify:
    - Restart web server

- name: Allow HTTP and HTTPS ports for IPv4
  iptables_raw:
    name: cdn_ports_ipv4
    weight: 20
    ipversion: "4"
    rules: |
      -A INPUT -p tcp -m tcp --dport 80 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 443 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT

- name: Allow HTTP and HTTPS ports for IPv6
  iptables_raw:
    name: cdn_ports_ipv6
    weight: 20
    ipversion: "6"
    rules: |
      -A INPUT -p tcp -m tcp --dport 80 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 443 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
