---
- name: Install basic firewall packages
  pacman:
    name: iptables
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: Set default IPv4 rules
  template:
    src: iptables.rules.j2
    dest: /etc/iptables/iptables.rules
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart iptables firewall

- name: Activate iptables service
  service:
    name: iptables
    enabled: yes
    state: started

- name: Set default IPv6 rules
  template:
    src: ip6tables.rules.j2
    dest: /etc/iptables/ip6tables.rules
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart ip6tables firewall

- name: Activate ip6tables service
  service:
    name: ip6tables
    enabled: yes
    state: started
...
