---
- name: Install basic firewall packages
  apt:
    name: nftables
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: Set default nftables rules
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart nftables firewall

- name: Activate nftables service
  service:
    name: nftables
    enabled: yes
    state: started
...
