---
- name: Install basic firewall packages
  pacman:
    name: iptables
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: Set default iptables rules
  template:
    src: iptables.rules.j2
    dest: /etc/iptables/iptables.rules
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart iptables firewall

- name: Activate iptables service
  service:
    name: iptables
    enabled: yes
    state: started
...
