---
- name: Install basic firewall packages
  pacman:
    name: iptables
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: Set default firewall rules
  template:
    src: "{{ item }}.rules.j2"
    dest: "/etc/iptables/{{ item }}.rules"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - iptables
    - ip6tables
  notify:
    - Restart iptables firewall
    - Restart ip6tables firewall

- name: Activate firewall services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - iptables
    - ip6tables
...
