---
- name: Install mail packages
  apt:
    name:
      - postfix
      - mailutils
      - procmail
      - mutt
      - dovecot-imapd
    update_cache: yes

- name: Allow email TCP port for IPv4
  iptables_raw:
    name: "mail_ipv4"
    table: "filter"
    ipversion: "4"
    weight: 20
    keep_unmanaged: no
    rules: |
      -A INPUT -p tcp -m tcp --dport 25 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
      -A INPUT -i tun0 -p tcp -m tcp --dport 143 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
      -A INPUT -i tun0 -p tcp -m tcp --dport 993 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT

- name: Allow email TCP port for IPv6
  iptables_raw:
    name: "mail_ipv6"
    table: "filter"
    weight: 20
    ipversion: "6"
    keep_unmanaged: no
    rules: |
      -A INPUT -p tcp -m tcp --dport 25 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
      -A INPUT -i tun0 -p tcp -m tcp --dport 143 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT
      -A INPUT -i tun0 -p tcp -m tcp --dport 993 --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j ACCEPT

- name: Copy postfix server config file
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart postfix

- name: Copy main aliases file
  template:
    src: aliases.j2
    dest: /etc/aliases
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - New aliases
    - Restart postfix

- name: Copy HELO access checks file
  template:
    src: helo_access_checks.j2
    dest: /etc/postfix/helo_access_checks
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Helo access checks
    - Restart postfix

- name: Copy Dovecot 10-mail.conf 
  template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart dovecot
...
