---
- name: Install "Router Advertisement Daemon" package
  apt:
    name: radvd
    update_cache: yes

- name: Copy "radvd" config file
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    owner: 0
    group: 0
    mode: 0644
  notify:
    - Restart radvd server
...
