---
- name: Restart DNS server
  service:
    name: named
    state: restarted

- name: Restore iptables rules
  command: iptables-restore /etc/iptables/iptables.rules

- name: Restore ip6tables rules
  command: ip6tables-restore /etc/iptables/ip6tables.rules
...
