---
- name: Install basic router packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iptables
    - iptables-persistent

- name: Copy router sysctl config file
  template:
    src: 10-router.conf.j2
    dest: /etc/sysctl.d/10-router.conf
    owner: 0
    group: 0
    mode: 0644
  notify:
    - Restart sysctl

- name: Set IPv4 forward rule
  iptables_raw:
    name: basic_forward_ipv4
    table: filter
    weight: 10
    ipversion: 4
    keep_unmanaged: no
    rules: |
      -A FORWARD  -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A FORWARD -o "{{ router_wan_interface }}" -j ACCEPT
  notify:
    - Restart firewall

- name: Configure NAT for IPv4
  iptables_raw:
    name: basic_nat
    table: nat
    weight: 10
    ipversion: 4
    keep_unmanaged: no
    rules: |
      -P PREROUTING ACCEPT
      -P INPUT ACCEPT
      -P OUTPUT ACCEPT
      -P POSTROUTING ACCEPT
      -A POSTROUTING -o {{ router_wan_interface }} -j MASQUERADE
  notify:
    - Restart firewall

- name: Set IPv6 forward rule
  iptables_raw:
    name: basic_forward_ipv6
    table: filter
    weight: 10
    ipversion: 6
    keep_unmanaged: no
    rules: |
      -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A FORWARD -o "{{ router_wan_interface }}" -j ACCEPT
  notify:
    - Restart firewall
...
