---
- name: Install DNS packages
  pacman:
    name: [ 'bind', 'bind-tools', 'icu' ]
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: Enable bind service
  systemd:
    name: named
    enabled: yes

- name: Copy main bind config file
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0640
  notify:
    - Restart DNS server

- name: Copy dns key file
  copy:
    src: dns_key.key
    dest: "{{ dns_key_file }}"
    owner: root
    group: named
    mode: 0440
  notify:
  - Restart DNS server

- name: Allow DNS ports for IPv4
  lineinfile:
    path: /etc/iptables/iptables.rules
    insertafter: "-A INPUT -p tcp -m conntrack --ctstate NEW -m tcp --dport 22 -j ACCEPT"
    line: "{{ item }}"
  with_items:
    - "-A INPUT -p tcp -m tcp --dport 53 --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j ACCEPT"
    - "-A INPUT -p udp -m conntrack --ctstate NEW -m udp --dport 53 -j ACCEPT"
  notify:
    - Restore iptables rules

- name: Allow DNS ports for IPv6
  lineinfile:
    path: /etc/iptables/ip6tables.rules
    insertafter: "-A INPUT -p tcp -m conntrack --ctstate NEW -m tcp --dport 22 -j ACCEPT"
    line: "{{ item }}"
  with_items:
    - "-A INPUT -p tcp -m tcp --dport 53 --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j ACCEPT"
    - "-A INPUT -p udp -m conntrack --ctstate NEW -m udp --dport 53 -j ACCEPT"
  notify:
    - Restore ip6tables rules
...
